### ISSUE TITLE
Return the generated data in a string.

### ISSUE THREAD

**Issue by andreybatalof** [Bukashk0zzz/YmlGenerator#24]
When working with a small product catalog, I want to generate and give it away each time a bot accesses without using files.

Acceptance criteria: the generated product catalog can be obtained as a string variable.

**Comment by floor12** [comment]
@Bukashk0zzz hello, will you merge this PR?

**Comment by andreybatalof** [comment]
> @Bukashk0zzz hello, will you merge this PR?

Yes, in the near future I want to correct the remarks on pr and try to merge it again.

**Comment by floor12** [comment]
Perfect. Thanks for your work guys.

**Comment by Bukashk0zzz** [comment]
I add this feature in v1.11.0 release https://github.com/Bukashk0zzz/YmlGenerator/releases/tag/v1.11.0


Example how to get YML string:

```php
        $settings = (new Settings())
            ->setReturnResultYMLString(true)
        ;
        $value = (new Generator($settings))
            ->generate(new ShopInfo(), [], [], [], []);
```
