### ISSUE TITLE
Ability to add enable_auto_discounts tag for offers and shop info

### ISSUE THREAD

**Issue by Taarim** [Bukashk0zzz/YmlGenerator#30]
https://yandex.ru/support/partnermarket/elements/enable_auto_discounts.html

Было бы полезно добавить возможность управлять тегом enable_auto_discounts глобально из ShopInfo и индивидуально в Offers, чтобы все было из коробки. Сейчас проблему можно решить наследованием. Предложение больше для  удобства

**Comment by Bukashk0zzz** [comment]
Сделал релиз https://github.com/Bukashk0zzz/YmlGenerator/releases/tag/v1.11.1
Спасибо за реквест.
