### ISSUE TITLE
Yml file

### ISSUE THREAD

**Issue by merirosewins** [Bukashk0zzz/YmlGenerator#37]
- name: google-api-fetch-token-action
  uses: cardinalby/google-api-fetch-token-action@1.0.0
 
How do I use that ^ & what is a yml file how do I paste tokens into my yml file??

**Comment by Bukashk0zzz** [comment]
Hi, I think you add issue to wrong project.

**Comment by Bukashk0zzz** [comment]
This project doesn't have any dependencies.
