### ISSUE TITLE
добавить размеры товаров

### ISSUE THREAD

**Issue by vodnicearv** [Bukashk0zzz/YmlGenerator#40]
https://yandex.ru/support/partnermarket/offers.html#offers

![image](https://user-images.githubusercontent.com/14403446/111042861-1e8cfc80-8448-11eb-856c-0396cf1a8e25.png)

было бы полезна функция для добавления размеров товара в упаковке

**Comment by rodnyco** [comment]
Да, хорошая идея. Поработаю над этим на выходных.

**Comment by Bukashk0zzz** [comment]
Done.
